### ISSUE TITLE
add TermExtractor that extracts terms from Lucene index

### ISSUE THREAD

**Issue by kojisekig** [NLP4L/attic-nlp4l#22]

**Comment by samfukuda** [comment]
G’day Sekiguchi-san,

Your tutorial in Japanese is telling steps to extract tech term from lucene index. And it requiring to execute examples/index_ldcc_sports-watch.scala.
so I wish you will put it on there.

ciao,
-su

**Comment by kojisekig** [comment]
Absolutely.

But I don't know why github doesn't have the file, because I see it in my local and there is no message when I execute "git status".

Anyway, I'll fix it soon.

**Comment by kojisekig** [comment]
I've added the file using git add with -f option. You should see it now.

I think our .gitignore contains problematic line...

Thank you for your report!

**Comment by samfukuda** [comment]
yap, now verified existing and it makes terms.txt.

ciao,
-su
